### ISSUE TITLE
Where the video will get saved

### ISSUE THREAD

**Issue by riteshnewal** [myflashlab/downloadManager-ANE#1]
Hi,

This is not issue rather question
1. If I want to save video in IOS where it will save, in Album?
2. Same question for Android, will it save in Gallery?

Ritesh

**Comment by myflashlab** [comment]
They will be saved in File.DocumentDirectory take the following sample:

```actionscript
_ex.startDownload("http://myflashlab.com/showcase/Bully_Scholarship_Edition_Trailer.mp4", "dm", "Bully_Scholarship_Edition_Trailer.mp4");
```

The video file will be saved to "dm" folder both in Android and iOS. it will be displayed on the Android Gallery automatically but for iOS you need to take care of it yourself which is not the job of the download manager

**Comment by riteshnewal** [comment]
Ok Thanks.
