### ISSUE TITLE
null object reference when calling DM constructor

### ISSUE THREAD

**Issue by reckhoff** [myflashlab/downloadManager-ANE#10]
When debugging on an android device (I haven't tried iOS yet), the constructor is failing:
[Fault] exception, information=TypeError: Error #1009: Cannot access a property or method of a null object reference.
at com.myflashlab.air.extensions.dm.android::Android()
at com.myflashlab.air.extensions.dm::DM()

Below is my code. Note that if I run this in the simulator (Yes, i know the simulator isn't supported), it gets past the constructor all the way to startDownload. Thoughts on why, on an Android device (Android 4.4.2), the new DM() is throwing the null reference exception?

            var _ex:DM = new DM();

            _ex.addEventListener(DMEvent.ERROR, onError);
            _ex.addEventListener(DMEvent.PROGRESS, onProgress);
            _ex.addEventListener(DMEvent.COMPLETE, onComplete);

            trace("about to do it");
            _ex.startDownload("http://myflashlabs.com/showcase/Bully_Scholarship_Edition_Trailer.mp4", "dm", "Bully_Scholarship_Edition_Trailer.mp4");
            trace("download started");

**Comment by myflashlab** [comment]
Please watch the videos linked from here https://github.com/myflashlab/downloadManager-ANE/issues/5#issuecomment-174152494

**Comment by reckhoff** [comment]
Watching the videos didn't fix the problem. We have succesfully used your webview ane (and many other ANES) with no issues. The application xml looks like:
		<extensionID>com.myflashlab.air.extensions.webView</extensionID>
        <extensionID>com.myflashlab.air.extensions.downloadManager</extensionID>

and 
 			<activity android:name="com.doitflash.webView.Pick" android:theme="@style/Theme.Transparent" />
            <activity android:name="com.doitflash.downloadManager.MyActivity" />

We aren't worrying about iphone yet.

we are using air 16 which should be fine as your extension.xml requires 15.

**Comment by myflashlab** [comment]
That kind of error message means that the ANE is not implemented correctly in to the project but you're saying you have watched the videos and have used our other ANEs with no problem. So, That's weird!

would you try with the latest Air SDK? Air 16 is just too old. just a guess though. when you did the test, let me know and I'll have a closer look at this.

**Comment by reckhoff** [comment]
our App is using flex 4.14, air 16 which was released last march. We aren't in a position to upgrade to a newer version of air for that app at this point in time. As a test though, i will download the latest 4.15 air 20 from apache today and create a simple test app to see what happens. I'll post the results when i'm done.

Any way we can debug on our end?

more information. 
- We use JetBrains IntelliJ IDEA as our IDE.
- We use ant from the command line to do our official builds
- This particular test is currently android only but will eventually be on iOS as well.
- We've used your webview ane with no issues.
- We've used other vendor anes with no issues
- We've created our own anes with no issues
- We tried both 3.9.1 and 3.9.2 of download manager.

curious... what is the difference in the paid version vs. the free?

**Comment by myflashlab** [comment]
I should add that the Flex version actually does not matter much if you are not using the Flex framework. So only upgrading the Air SDK will be good enough usually.

> what is the difference in the paid version vs. the free?

Nothing, They will work exactly the same.

----------
Considering that you have used ANEs before, there must be a little mistake somewhere. Please make sure you are updating your Air SDK and also make sure you are using the latest ANE version of the download manager.

**Comment by reckhoff** [comment]
A simple test app using AIR 20 works. Same app using AIR 16 fails. I have not test 15, 17, 18, or 19.

For others to avoid the same issues, you might want to update your requirements to specify the minimum AIR version downloadManager requires. If you open the ANE with a zip utility, extension.xml specifies AIR 15 which implies that AIR 15+ will work.

**Comment by myflashlab** [comment]
Thanks for the input. always using the latest Air version is a good idea. we try to update the min Air version specified in the extension.xml too.
