### ISSUE TITLE
What am I doing wrong? (id is -1 and jobs-array is empty)

### ISSUE THREAD

**Issue by hpieper** [myflashlab/downloadManager-ANE#12]
What am I doing wrong?
(using demo-version)

`_ex = new DM();
_ex.addEventListener(DMEvent.NATIVE_LIB_DOWNLOAD_JOB_FINISHED, handleAssetsLoaderEvents);
var id:int = _ex.nativeAndroidDM_start("http://myflashlabs.com/showcase/Bully_Scholarship_Edition_Trailer.mp4", "/dm", "", "DM ANE!", "Download Manager Air Native Extension", true);
var arr:Array = _ex.nativeAndroidDM_getOnGoingJobs();`

Result: id is -1 and jobs-array is empty

**Comment by myflashlab** [comment]
When using the demo ANE, you should notice that:
> NOTICE: the demo ANE works only after you hit the "OK" button in the dialog which opens. in your tests make sure that you are NOT calling other ANE methods prior to hitting the "OK" button.

Explained here: https://github.com/myflashlab/downloadManager-ANE#demo-apk
