### ISSUE TITLE
not working on android 

### ISSUE THREAD

**Issue by Samikaraeen** [myflashlab/downloadManager-ANE#14]
if the file is  tooo big over 50 mb it will not work
on ios it work like a charm

any suggestions
i use the same code for both if the file is small it works fine

also 

NATIVE_LIB_DOWNLOAD_JOB_FINISHED is no found in the ane i have

**Comment by myflashlab** [comment]
Please read here: https://github.com/myflashlab/downloadManager-ANE/issues/15#issuecomment-223376243
