### ISSUE TITLE
Connection to file lost

### ISSUE THREAD

**Issue by c-andrews** [myflashlab/downloadManager-ANE#15]
Hi,
I am getting the following error on Android: "error: Connection to file lost". Could you tell me why this might happen? I don't have any issues on IOS using the same code base, just android. 

Thanks,
Chris

**Comment by myflashlab** [comment]
For the Android side, as suggested by Android, you should use the default DownloadManager Library. we have exposed that library to the Air developers. please read these lines: https://github.com/myflashlab/downloadManager-ANE/blob/master/FD/src/MainFinal.as#L206-L241
