### ISSUE TITLE
Not working on Android!!

### ISSUE THREAD

**Issue by llorenzo** [myflashlab/downloadManager-ANE#17]
Hello,

first I must admit that I'm a bit frustrated here. Grrr... I can't get the downloader to work on Android.
I have too download 13 videos à 25 mb each into the App. The app relies on this.

I did create a BatchDownloader which starts a new Download after the one before completes. That works on IOS.

On Android I get strange behavior like crashes without Errors. Even in the logcat I could not find anything then "process has died". This is frustrating since debugging takes a long time and doesn't get anywhere. The problems seem to be beyond the scope of my AS3 code.

So, I  tried the native downloader. Well it doesn't work either.

I called `dm.nativeAndroidDM_start("http://myflashlabs.com/showcase/Bully_Scholarship_Edition_Trailer.mp4", "/dm", "", "DM ANE!", "Download Manager Air Native Extension", true);`
Only one video as being cautious.

On my older 4.1.2 Android system it shows a download process in the notifier.
On the Samsung S5 mini 5.1.1 nothing is shown in the notifier.

Also I'm disappointed that there doesn't seem to be any progress information as an Event in AS3. This is in my opinion a very basic UX must have. DMEvent.ERROR, DMEvent.PROGRESS and DMEvent.COMPLETE just don't work in the native downloader.

When interval tracing the ongoing downloads I get no more info:
```
id : 26
name : 01_Vid_Rain.mp4
url : http://llorenzo.de/data/dma/DMA-SMALL/01_Vid_Rain.mp4
dis : /storage/sdcard0dma
```
But has the download really started? Is anything downloading? I can't tell!!!

Suddenly I get an 
`Error #1132: Invalid JSON parse input`
it is thrown by the `dm.nativeAndroidDM_getOnGoingJobs()`

`DMEvent.NATIVE_LIB_DOWNLOAD_JOB_FINISHED`
Is never fired at all. Even if I skip the `dm.nativeAndroidDM_getOnGoingJobs()`

I put all manifest entries in the android xml. I use the basic code from https://github.com/myflashlab/downloadManager-ANE/blob/master/FD/src/MainFinal.as#L206-L241

Unfortunately I have a release date next week. I spent many hours/days trying to find out how it could work. It does not work. Downloading 13 Videos is just not possible with you ANE. What I'm I going to say to my client????

Any chance you can fix the downloader and make it stable and work?

**Comment by myflashlab** [comment]
While we are investigating this, would you please confirm if you have added the [required manifest setup for Android?](https://github.com/myflashlab/downloadManager-ANE#air-xml-manifest-1)

**Comment by myflashlab** [comment]
Will you be able to send us a demo .APK? because we are not able to reproduce the problem. It's loading just fine!

**Comment by myflashlab** [comment]
by having a closer look at your message, where you said ```dis : /storage/sdcard0dma``` it seems like you have missed the initial ```/``` for the path that the downloaded file must drop into.

Also, please note that if you are using the official Download manager lib from Android, the download progress will be shown in the devices notification center and nothing much is returned to the Air side. If you need to receive the download progress inside your app, you should use the other method.

> On my older 4.1.2 Android system it shows a download process in the notifier. On the Samsung S5 mini 5.1.1 nothing is shown in the notifier.

We even tested with Android 6+ and it works normally. a demo .apk would be great.

**Comment by llorenzo** [comment]
HI, thanks for coming back to this. As you can tell I'm a bit stressed out at an important part of the current project. In the moment it looks as if I have got a stable version running. The problems described above seem to come from a cache problem in the compiler. The download process would sometime run through and another time not. There was no coding or manifest problems on my side. After installing the current version of IntelliJ and invalidating all caches the build became stable again. The AIR SDK 21 was kept. So in the end I went back to my previous version of downloading a file at a time in a queue which gives proper feedback to the user. For now it does not need any further investigation. Thank, and sorry for the stress. Martin
