### ISSUE TITLE
app crashes

### ISSUE THREAD

**Issue by galaxybeing** [myflashlab/downloadManager-ANE#2]
I set up the dl manager to download a zip file then upzip it with the zipmanager.  it got through the download and presented the zip ok dialog and crashed the app.  I tried putting a dispose() in there after the download but it still crashed it.

Also, what are the directories that we should use for downloading and unzipping to?  Logic would say to download to a temp directory and unzip to the applicationStorageDirectory but I am getting the impression that won't work.  What are the directories you suggest or that you know will work or won't work?

**Comment by myflashlab** [comment]
you should use File.DocumentsDirectory for the download and unzipping. you can later move them away anywhere you like.

**Comment by galaxybeing** [comment]
I think I fixed the crashing issue.  But what are your comments on the directories?  I think I saw a comment from you that you can only download to the sd card?  So specifying documentsDirectory for downloading?  And then unzipping to the applicationStorageDirectory?

**Comment by galaxybeing** [comment]
i tried unzipping to the applicationStorageDirectory and it seemed like it did it ok, but right after I checked for a file and it wasn't there.  Can the extensions only access the documentsDirectory ?  Where is the appropriate place for game assets that couldn't be included in the main app?  As soon as I figure this out and get it working I'm going to buy both extensions.

**Comment by galaxybeing** [comment]
It was downloading and about halfway it got an error
ERROR: Connection to file failed!
So I guess I would wait a period of time or test if the connection is back up and then to restart the download, do what?  Use the same command again?  startDownload(... with the same parameters?

**Comment by galaxybeing** [comment]
I just tried to export a release build for iOS (I'm on Windows) and got this error:
Compilation failed while executing : ld64
Doing a little research I found something that said I can only use these extensions on a Mac?  Is that the case?

**Comment by myflashlab** [comment]
>  Can the extensions only access the documentsDirectory

Yes, you should use DocumentsDirectory. when the job is finished, you can move them anywhere else you like

> Use the same command again? startDownload(... with the same parameters

Yes

> just tried to export a release build for iOS (I'm on Windows) and got this error

* You can't run the extension on simulator
* if you are on a windows 32-bit you can't compile for iOS at all!

**Comment by galaxybeing** [comment]
I'm on Windows 64bit and I've been compiling for iOS for the past 3 years with 5 other ANEs.  I only need a Mac to submit the binary.

**Comment by myflashlab** [comment]
then you should be fine. we are also running on Windows 64-bit and everything works normally. sp, make sure you are using the latest Air SDK that's what I can think of. Also make sure sure you are successfully compiling the demo projects.

**Comment by galaxybeing** [comment]
I pulled you ANEs out and I'm still getting that error, so it's something else.

**Comment by galaxybeing** [comment]
Here is the problem I am having now.  I have 5 ANEs from Milkman games in my project

 

                                <extensionID>com.milkmangames.extensions.StoreKit</extensionID>

                                <extensionID>com.milkmangames.extensions.GoViral</extensionID>

                                <extensionID>com.milkmangames.extensions.EasyPush</extensionID>

                                <extensionID>com.milkmangames.extensions.CoreMobile</extensionID>

                                <extensionID>com.milkmangames.extensions.RateBox</extensionID>

 

It takes less than 2 minutes to build an ipa file.

 

If I add EITHER  the download manager OR the zip manager, without actually calling them, it compiles successfully and takes about the same amount of time, less than 2 minutes.  

 

But if I add BOTH of your ANEs, the time goes to 15  minutes plus.  I don’t know if it will complete or not -  I cancel it because obviously something is wrong.  Do you have any ideas?  Thanks.   I’m using AIR SDK 18 released version.
