### ISSUE TITLE
open File

### ISSUE THREAD

**Issue by Samikaraeen** [myflashlab/downloadManager-ANE#3]
i have download an xml file using the DM ane on IOS
but i cant read it , i want to open it and read it but it always gives me #3003 error 
can u send me code on how to get the path 
the download is ok but i want to open the file

**Comment by myflashlab** [comment]
do you have this problem is you try to download anything else? I mean in other formats? like a zip file for example?

**Comment by Samikaraeeb** [comment]
it must be xml i need to open that file 
thi sisi the code i use
_ex.startDownload("http://192.168.1.87/EasySyncWs/x.xml",  "data","data.xml",true);
how can i open it

**Comment by Samikaraeeb** [comment]
i have IOS can u tell me where does it save 
i tried File.applicationDirectory.resolvePath("data/data.xml")  not working
File.applicationStorageDirectory.resolvePath("data/data.xml"); not working 
 how can i access it 
plz answer me

**Comment by myflashlab** [comment]
Thanks for the extra information about the problem. Please try
File.documentsDirectory instead of the other two you tried.

On Tuesday, September 15, 2015, Samikaraeeb <notifications@github.com>
wrote:

> i have IOS can u tell me where does it save
> i tried File.applicationDirectory.resolvePath("data/data.xml") not working
> File.applicationStorageDirectory.resolvePath("data/data.xml"); not working
> how can i access it
> plz answer me
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/downloadManager-ANE/issues/3#issuecomment-140435020>
> .
>


-- 
Sent from iPhone
