### ISSUE TITLE
Save the downloaded data to external sdcard of android device.

### ISSUE THREAD

**Issue by idzone** [myflashlab/downloadManager-ANE#4]
According to this link - ((http://developer.android.com/guide/topics/data/data-storage.html#AccessingExtFiles))  we can read and write data to external sdcard. Files.documentDirectory, Files.userDirectory, Files.desktopDirectory all points to external part of my internal storage.
I want to save downloaded data to EXTERNAL SDCARD of my ANDROID device. Is it possible to do that using your ane?

**Comment by myflashlab** [comment]
Considering that most devices nowadays are coming with an embeded sdcard, we have not played with mountable memory sticks much. saying that, the download manager helps you download the file somewhere on sdcard and then when the file is downloaded, you can move it anywhere else using any methods you like but this feature is not something necessary for this extension.
