### ISSUE TITLE
Error #3500: The extension context does not have a method with the name command.

### ISSUE THREAD

**Issue by vbakalov** [myflashlab/downloadManager-ANE#5]
Hi,

I'm trying to use the commercial version of the ANE library and I'm debugging on Android platform from IntelliJ environment. I can successfully compile my application but when I debug  I receive the error:

```Error #3500: The extension context does not have a method with the name command.```

I'm trying the example code below and I receive the error when calling the _ex.startDownload(...)
```
var _ex:DM = new DM();


        _ex.addEventListener(DMEvent.ERROR, onError);
        _ex.addEventListener(DMEvent.PROGRESS, onProgress);
        _ex.addEventListener(DMEvent.COMPLETE, onComplete);


        _ex.startDownload("http://myflashlabs.com/showcase/Bully_Scholarship_Edition_Trailer.mp4", "dm", "Bully_Scholarship_Edition_Trailer.mp4");
```
Any help will be appreciated.

**Comment by myflashlab** [comment]
are you trying to run on a simulator? please use a real device instead. also take a look at these videos. you might find them very helpful.

https://www.youtube.com/watch?v=Oubsb_3F3ec&list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O
