### ISSUE TITLE
ANE crashes when trying to use it on the PC

### ISSUE THREAD

**Issue by matyasatfp** [myflashlab/downloadManager-ANE#7]
When developing our apps with this extension on a PC calling new DM() results in this error:

````
exception, information=ArgumentError: Error #3500: The extension context does not have a method with the name command.
at flash.external::ExtensionContext/_call()
at flash.external::ExtensionContext/call()
at com.myflashlab.air.extensions.dm.android::Android()
at com.myflashlab.air.extensions.dm::DM()
````

It would be nice if the ANE provided a fallback for PCs and we did not needed to write a workaround code that never gets called in production

**Comment by myflashlab** [comment]
You're right, the extension runs on real devices only. we are going to add a general property to check the environment first so it won't throw the ugly error message on simulators.

**Comment by myflashlab** [comment]
To avoid this, we have developed the [ANE Inspector Tool](https://github.com/myflashlab/ANE-Inspector-Tool)
