### ISSUE TITLE
File download location

### ISSUE THREAD

**Issue by c-andrews** [myflashlab/downloadManager-ANE#9]
Where is the downloaded file stored? is the "path" relative or an absolute path?:

Is the file placed in File.documentsDirectory or File.applicationStorageDirectory?

_ex.startDownload("myurl.com/myfile.zip", "dm", "myfile.zip");

**Comment by myflashlab** [comment]
copied from our sample project, ```dm``` means a folder in the root of your device.

```actionscript
_ex.startDownload("http://myflashlabs.com/showcase/Bully_Scholarship_Edition_Trailer.mp4", "dm", "Bully_Scholarship_Edition_Trailer.mp4");
```

so, ```dm``` means ```File.documentsDirectory.resolvePath("dm");```

When using the Android builtin downloadManager API though, you should be careful about the initial ```/``` i.e:

```actionscript
_ex.nativeAndroidDM_start("http://myflashlabs.com/showcase/Bully_Scholarship_Edition_Trailer.mp4", "/dm", "", "DM ANE!", "Download Manager Air Native Extension", true);
```

here, the ```/dm``` again means ```File.documentsDirectory.resolvePath("dm");```
